"""create tables

Revision ID: ba1ae4093035
Revises: 
Create Date: 2023-11-01 16:06:56.042461

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ba1ae4093035'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('brand', sa.VARCHAR(length=64), nullable=False),
                    sa.Column('model', sa.VARCHAR(length=64), nullable=False),
                    sa.Column('engine_type', sa.VARCHAR(length=64), nullable=False),
                    sa.Column('drive_type', sa.VARCHAR(length=64), nullable=False),
                    sa.Column('year_of_production', sa.INTEGER(), nullable=False),
                    sa.Column('vin', sa.INTEGER(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('detail',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('category', sa.VARCHAR(length=64), nullable=False),
                    sa.Column('model', sa.VARCHAR(length=64), nullable=False),
                    sa.Column('price', sa.INTEGER(), nullable=False),
                    sa.Column('is_available', sa.BOOLEAN(), server_default='f', nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('feedback',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('user_name', sa.VARCHAR(length=64), nullable=False),
                    sa.Column('text', sa.VARCHAR(length=256), nullable=False),
                    sa.Column('date', sa.DATE(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('person',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
                    sa.Column('surname', sa.VARCHAR(length=64), nullable=False),
                    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('promotion',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('type', sa.VARCHAR(length=64), nullable=False),
                    sa.Column('discount_percentage', sa.INTEGER(), nullable=False),
                    sa.Column('end_date', sa.DATE(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('service',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
                    sa.Column('price', sa.INTEGER(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service')
    op.drop_table('promotion')
    op.drop_table('person')
    op.drop_table('feedback')
    op.drop_table('detail')
    op.drop_table('car')
    # ### end Alembic commands ###
