"""create FK car-detail

Revision ID: f49488aa6e5b
Revises: ba1ae4093035
Create Date: 2023-11-04 12:04:23.915451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f49488aa6e5b'
down_revision: Union[str, None] = 'ba1ae4093035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail', sa.Column('car_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'detail', 'car', ['car_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detail', type_='foreignkey')
    op.drop_column('detail', 'car_id')
    # ### end Alembic commands ###
